sonar.projectKey=doc_platform-backend
sonar.projectName=doc_platform-backend
sonar.projectVersion=1.0

sonar.sources=core,doc_platform
sonar.sourceEncoding=UTF-8
sonar.language=python

sonar.inclusions=**/*.py
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**,**/env/**,**/*.pyc

sonar.coverage.exclusions=**/settings.py,**/asgi.py,**/wsgi.py,**/email_service.py

sonar.security.hotspots.inheritFromParent=false
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S2068
sonar.issue.ignore.multicriteria.e1.resourceKey=**/tests.py

sonar.tests=core
sonar.test.inclusions=**/tests/**/*.py,**/test_*.py
sonar.python.coverage.reportPaths=coverage.xml