# Generated by Django 5.2.1 on 2026-04-23 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_auditlog_id_alter_document_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('completo', 'Completo'), ('diferencial', 'Diferencial'), ('incremental', 'Incremental')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('size_kb', models.FloatField(default=0.0)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='success', max_length=20)),
            ],
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='auditlog_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='auditlog_action_idx'),
        ),
    ]
